### ISSUE TITLE
[1.11.2] Mod will not load

### ISSUE THREAD

**Issue by Firebirdie713** [modmuss50/Fluxed-Redstone#28]
I am trying to use your 1.11.2 version of the mod in a singleplayer, and the mod will not load properly.

The error shown in the log is as follows:

[15:20:50] [Client thread/WARN]: * The API CoFHAPI from source C:\Users\User\AppData\Roaming\.minecraft\mods\FluxedRedstone-2.6.0.54.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[15:20:50] [Client thread/WARN]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)
[15:20:50] [Client thread/WARN]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)
[15:20:50] [Client thread/WARN]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)
[15:20:50] [Client thread/WARN]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536)
[15:20:50] [Client thread/WARN]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:229)
[15:20:50] [Client thread/WARN]: *  at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)...
[15:20:50] [Client thread/WARN]: ****************************************

**Comment by modmuss50** [comment]
I need the whole log

**Comment by Firebirdie713** [comment]
Sorry about that!

I have attached a copy of the log.


[latest_log.txt](https://github.com/modmuss50/Fluxed-Redstone/files/794766/latest_log.txt)

**Comment by modmuss50** [comment]
Nothing abnormal in the logs? What do you mean wont load?

**Comment by Firebirdie713** [comment]
When I load Minecraft, the cables are not listed in JEI.  For a while it would not be listed in the Mod Options list either, but that seems to have fixed itself.

**Comment by modmuss50** [comment]
There is another bug where they show under Minecraft for some reason.
